[build]
  # Comando para instalar dependências das funções
  command = "npm install --prefix netlify/functions || echo 'Instalação falhou, continuando...'"
  # Diretório das Netlify Functions
  functions = "netlify/functions"
  # Diretório de publicação do frontend
  publish = "."

[[redirects]]
  # Redireciona todas as rotas para index.html (SPA)
  from = "/*"
  to = "/index.html"
  status = 200

# Variáveis de ambiente para produção
[context.production.environment]
  # Placeholder para MONGODB_URI (definir no painel do Netlify)
  MONGODB_URI = ""